### ISSUE TITLE
MCTS performs worse with 10k iterations than with 1k

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/MCTS.jl#10]
See test/performance.jl

Do we know why this is happening?

**Comment by mykelk** [comment]
Poor choice of exploration parameter, @neosado?

**Comment by zsunberg** [comment]
Hmm, right now this issue isn't being reproduced for me (in the test I am running now 10k is performing better than 1k). I haven't figured out what I changed that made the difference.
