### ISSUE TITLE
depth parameter is not used by DPWSolver

### ISSUE THREAD

**Issue by MathildeJeannin** [JuliaPOMDP/MCTS.jl#109]
Hi ! 

As the title says, the depth parameter is not used by DPWSolver. 
I dug a bit and found out that the function estimate_value defined in domain_knowledge.jl line 65 will use the parameter max_depth set by default to 50 instead of depth that one should set when calling DPWSolver. It will only use depth if max_depth = -1. 
According to dpw_types.jl, estimate_value is set by default to RolloutEstimator(RandomSolver(rng)). Calling DPWSolver(estimate_value = RolloutEstimator(RandomSolver(rng), max_depth=-1)) would do the trick but it is not obvious in the doc that depth is useless if max_depth is not set to -1. 

My issue here is not really an issue but did I miss something ? Should it be easier to use my depth parameter ? Or should it be in the doc ? 

Thanks !

**Comment by zsunberg** [comment]
Wow! Thanks for catching this very subtle issue. I think the behavior is correct (See #88 for more context), but the documentation is wrong. I will update it.
