### ISSUE TITLE
location of tree/ mutability of policy object

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/MCTS.jl#11]
Right now, `tree` is a member the solver object.

This doesn't make sense because, to interpret the tree, one needs access to `mdp` and `action_map`, which are members of the policy. Also if more than one policy is created from the solver, there could be strange effects when the tree is mutated.

We could move `tree` to the policy, but this is still a little strange because then the policy is mutated on every call to `action()`. Is the mutation a good behavior? Or should the policy object be an immutable (but perhaps not deterministic?) mapping from states to actions? (In this case we would have to have some sort of mutable policy state if we want to carry tree data for repeated use in the same simulation)

**Comment by mykelk** [comment]
I'm okay with it being moved to the policy. And it's okay if it gets mutated.

**Comment by zsunberg** [comment]
Max, I made this change. If you're ok with it you can close this issue

**Comment by etotheipluspi** [comment]
Yep that works for me
