### ISSUE TITLE
Rename "Policy" to "Planner"

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/MCTS.jl#18]
"Planner" might be a nice word to use for a `POMDPs.Policy` that represents an online solver. That way it is clear that it is not a `POMDPs.Solver`, but it is also not just a precomputed static policy that maps states to actions without extra computation.

**Comment by zsunberg** [comment]
"Planner" is what I am using in the POMCP package now by the way

**Comment by mykelk** [comment]
It's a representation for a policy. The fact that it can require a bit of computation doesn't mean that it isn't a policy. You can also specify policies that wouldn't be considered the result of planning (e.g., just a static heuristic policy).

**Comment by zsunberg** [comment]
Today @rejuvyesh  noted that he though MCTSPolicy was a weird name, and @etotheipluspi agreed he thought that MCTSPlanner might sound better. I think @mykelk thought that I was proposing changing `POMDPS.Policy` to something involving "Planner" - that is not the plan; the plan is merely to rename the MCTS policy types since they work more like planners rather than predetermined mappings from states to actions. I think I might implement this change after the end of AA228

**Comment by mykelk** [comment]
I think we want to limit the number of concepts. We have Solvers and we have Policies. Throwing in Planner will just be confusing. A Policy is something that takes as input information about the state and generates an action. This is precisely what MCTSPolicy does. _The fact that the amount of computation required for generating the action is a bit more than other methods does not make this not a policy._

**Comment by zsunberg** [comment]
Yes, it will still be a policy: `type MCTSPlanner <: Policy` There will be no new official concepts added to POMDPs.jl.

**Comment by mykelk** [comment]
Still, I do not see the value in doing this. It's still a Policy and will be treated just like all the other policies by the experimenter.

**Comment by zsunberg** [comment]
(this was done a while ago)
