### ISSUE TITLE
Does MCTS.jl support number of actions varying with current state?

### ISSUE THREAD

**Issue by rcnlee** [JuliaPOMDP/MCTS.jl#2]
Hello,

The action space in my problem changes depending on current state.  I am trying to follow the POMDPs.jl interface where I see two functions:

``` julia
actions(mdp::POMDP) # returns the action space
actions(mdp::POMDP, s::State, as::ActionSpace) # fills the action space with the actions available from state s
```

where my understanding is that the first one returns the action space for the entire problem, while the second one gives the action space reachable from the current state s.  

When I look at the source in vanilla.jl in the simulate() function, it looks like only the first version is called (along with n_actions) and not the second state-specific version.  The state-specific version does look like it is being used in RandomPolicy in policies.jl though.

Does MCTS.jl support state-dependent action spaces at the moment?

Thanks!

**Comment by etotheipluspi** [comment]
In short, MCTS.jl does not currently support state dependent actions. 

As you note, the RandomPolicy, does sample from a subspace of the action space that is available only from the current state of interest. In other words, it uses that state dependent `actions(mdp::POMDP, s::State, as::ActionSpace)` function call. However, the current implementation assumes all the state nodes in the tree have the same number of actions (same cardinality as the whole action space), which makes sampling from a subset of the action space useless. 

One naive approach to deal with this would be to keep an action map at each state node of the tree along with the Q values and the counts. This may actually not add too much compute time and do exactly what you want. 

What are your thoughts?

**Comment by zsunberg** [comment]
I think we should support a state-dependent action space. I, for one, need this for my research. I am going to add this in the aggregation branch, and I'll try to benchmark it to see if there is a large performance loss (I doubt there will be).

**Comment by mykelk** [comment]
Good plan.

**Comment by zsunberg** [comment]
This was fixed in the aggregation merge
