### ISSUE TITLE
Visualization documentation: Tree does not show up in notebook on github

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/MCTS.jl#21]

**Comment by zsunberg** [comment]
https://github.com/JuliaPOMDP/MCTS.jl/blob/master/notebooks/Test_Visualization.ipynb

**Comment by zsunberg** [comment]
probably the solution is to host this notebook on some website designed to host jupyter notebooks

**Comment by mykelk** [comment]
It doesn't seem to show up [here](https://nbviewer.jupyter.org/github/JuliaPOMDP/MCTS.jl/blob/master/notebooks/Test_Visualization.ipynb) either.

**Comment by zsunberg** [comment]
Fixed on the nbviewer website... trying to see if I can figure out what's going on on github

**Comment by zsunberg** [comment]
It works on the nbviewer website now - I think that's as good as we're going to get. Github seems to just strip out the javascript.
