### ISSUE TITLE
Is there a way to include == and hash as requirements?

### ISSUE THREAD

**Issue by chelseas** [JuliaPOMDP/MCTS.jl#26]
Is there any way to include == and hash (for states) as requirements that show up when you call @requirements_info MCTSSolver() MDP() state()
?

**Comment by zsunberg** [comment]
Yes, I think that would catch a lot of bugs, but it takes a little thinking to implement, and it may not be very robust. To show the checkbox, we have to have a way to define `POMDPs.implemented(::typeof(==), TT)`. `method_exists(==, Tuple{T,T})` always returns `true` for any type `T`, even if the user has not implemented anything, so we can't use that.

The best thing I can think of is
```julia
function POMDPs.implemented(::typeof(==), tt::Type)
    m = which(==, tt)
    return !m.sig == Tuple{typeof(==), Any, Any}
end
```
This would go in  POMDPs.jl. This seems kind of fragile, but maybe it's ok. We would also have to handle both versions of `hash` and `isequal`.

I'll think about this and maybe implement it somewhere down the line. It would be a good tiny project if someone wants to understand the inner workings of the requirements specification system or propose a change to it that makes this easier (@MaximeBouton?).

**Comment by zsunberg** [comment]
For now we can certainly add it to the list of requirements, but it will always show up with a `[✓]` next to it.

**Comment by zsunberg** [comment]
maybe for requirements, instead of just having `[✓]` or `[X]`, we should also have an option to display `[!]` no matter what and point to the file and line number that it is finding

**Comment by zsunberg** [comment]
There are warnings for this now.

**Comment by bisraelsen** [comment]
Not sure if the warnings are still working or not, but I just learned that `hash` and `isequal` have to be implemented the hard way. Somehow it got past me; not sure if I missed something, or what... I'm running with the following versions:

```
[e12ccd36] MCTS v0.4.7
[182e52fb] POMDPPolicies v0.4.1
[e0d0a172] POMDPSimulators v0.3.12
[a93abf59] POMDPs v0.9.3
```

**Comment by zsunberg** [comment]
Thanks for reporting - I think I removed them because the default hash and equals implementations for immutable objects now work correctly, and the way I was checking was somewhat of a hack.

I think a better warning now would be to check if the state is mutable and recommend using immutable objects instead.

Are you using mutables?

**Comment by bisraelsen** [comment]
@zsunberg , yes I have been using mutable states although now that i'm aware that using immutables fixes the issue I can easily switch.

That is a pernicious kind of bug that sort of works, but not really... warning for immutable objects sounds like a great idea.
