### ISSUE TITLE
pruning actions

### ISSUE THREAD

**Issue by unhandyandy** [JuliaPOMDP/MCTS.jl#42]
Here my ignorance of mcts is combining with my ignorance of Julia.  What is the idiomatic way to limit the search to only those actions which are possible in a given state?  In GridWorld this is handled by having the transition function return the starting state unchanged, but that seems incredibly inefficient - with that approach a significant number of search nodes my involve impossible actions.

I thought perhaps I should implement 

`function POMDPs.actions(::TTTGame,s::TTTState)`

in addition to 

`function POMDPs.actions(::TTTGame)`

but MCTS.jl seems to support only the latter.

Perhaps the way to handle an impossible action is to transition to a terminal state with a negative reward?

**Comment by zsunberg** [comment]
You were correct at first - POMDPs.actions(::TTTGame, ::TTTState) should
allow this, and MCTS should support it.

What is leading you to think MCTS doesn't support it?

- Zach

**Comment by unhandyandy** [comment]
Oops, you're right, I didn't look closely enough at the error message.  Sorry 'bout that.
