### ISSUE TITLE
Where is the reward function called?

### ISSUE THREAD

**Issue by unhandyandy** [JuliaPOMDP/MCTS.jl#43]
Where in your code is the user defined `reward` function called?  I just grepped the src dir and couldn't find it anywhere.

The reason I ask is that I've experimented by reversing the signs of my reward function and it had no effect at all on `action(policy,state)`.

**Comment by zsunberg** [comment]
generate_sr() is called here:
https://github.com/JuliaPOMDP/MCTS.jl/blob/4c5e9d9400bbf0a070d916d49bf8e46dde80826d/src/vanilla.jl#L175

The default implementation of generate_sr() (to automatically provide the generative interface for problems implemented using the explicit interface) is here:
https://github.com/JuliaPOMDP/POMDPs.jl/blob/580241c493cb3f6b80d5127913d244cbeb6c52fa/src/generative_impl.jl#L55
That's where reward() gets called.

Have you implemented generate_sr() by hand? If you have explicitly implemented it, it will override the default that uses reward().

**Comment by unhandyandy** [comment]
I installed MCTS using Pkg.add.  I don't see generative_impl.jl in the src dir.

Oops, I was looking in MCTS, not POMDPs

**Comment by zsunberg** [comment]
Yeah, it is part of POMDPs.jl

**Comment by unhandyandy** [comment]
I see what my problem was, to simulate a two-player game I need to set the discount to -1.  It's now playing perfect tic-tac-toe.  Thanks for your help.
