### ISSUE TITLE
UCB choice?

### ISSUE THREAD

**Issue by unhandyandy** [JuliaPOMDP/MCTS.jl#44]
Have you thought about making the UCB a user definable property of the mctssolver type, as you did with init_Q?

**Comment by zsunberg** [comment]
Yeah, see #14 . Would that be useful to you? If so, I can probably find time to implement it tomorrow.

**Comment by unhandyandy** [comment]
No hurry, I've just over written best_sanode_UCB.

Also this by itself would useless without changing the StateNode type to include the state (my other issue yesterday).  What I'm trying to do is implement the AlphaZero algorithm using Flux and MCTS.  In that the UCB function depends on the neural net applied to the current state.

**Comment by zsunberg** [comment]
Right, yeah it should be configurable and there needs to be a way to access the state.

**Comment by zsunberg** [comment]
the discussion for this is moving to #14

**Comment by zsunberg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [MCTS Criterion customization](https://trello.com/c/lovqpZqR/9-mcts-criterion-customization)
