### ISSUE TITLE
simulate: takes state or state node?

### ISSUE THREAD

**Issue by unhandyandy** [JuliaPOMDP/MCTS.jl#50]
It seems that before PR48 the signature of simulate in vanilla was
simulate(policy::AbstractMCTSPlanner, state, depth::Int64)
where state was a State, but it is now
simulate(planner::AbstractMCTSPlanner, node::StateNode, depth::Int64).
So now to get the tree started we need to give it not the initial state of the system, but rather the initial state node. Of course I know how to create the initial state, but what's the recipe for creating the initial state node? Weren't nodes previously hidden from the user?

**Comment by zsunberg** [comment]
Yeah, you're correct.

If the tree already has the node in it, there is a dictionary called state_map to find it. If it doesn't have the node, then you would have to use `insert_node!` to insert it (`insert_node!` also returns the newly inserted node)

I just created the function `get_state_node` to make this easier. The three-argument version automatically creates a new node if it doesn't already exist.

**Comment by zsunberg** [comment]
Feel free to reopen if that doesn't make sense!

**Comment by unhandyandy** [comment]
Thanks!
