### ISSUE TITLE
Error Installing MCTS

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPOMDP/MCTS.jl#53]
Hello, Here is the error I get when Installing MCTS: 

```
`julia> import Pkg; Pkg.add("MCTS")
 Resolving package versions...
ERROR: Error when installing package MCTS:
HTTP.ExceptionRequest.StatusError(404, HTTP.Messages.Response:
"""
HTTP/1.1 404 Not Found
Server: openresty/1.13.6.2
Date: Tue, 07 May 2019 19:53:49 GMT
Content-Type: text/html
Content-Length: 175
Connection: keep-alive

""")
Stacktrace:`
```

**Comment by logankilpatrick** [comment]
Specifically, the installation here: https://github.com/JuliaPOMDP/MCTS.jl#installation

is not working. @zsunberg

**Comment by zsunberg** [comment]
Hmm... that is strange - it appears to be related to the github server? Maybe try again later, or try from a different connection.

**Comment by logankilpatrick** [comment]
Yep, very weird. Now it seems to be working fine.
