### ISSUE TITLE
Return estimate_value rather than 0 when depth=0 in simulate

### ISSUE THREAD

**Issue by fredcallaway** [JuliaPOMDP/MCTS.jl#54]
The current behavior makes sense for the default rollout estimator. But if you are using some other value estimator (e.g. an approximate value function) then it probably makes more sense to return that estimated value.

**Comment by zsunberg** [comment]
Yeah, I think that makes sense, want to submit a PR?

**Comment by zsunberg** [comment]
(I will fix it in a few days otherwise)

**Comment by fredcallaway** [comment]
Sure, happy to

**Comment by BoZenKhaa** [comment]
Maybe this can be closed now?
