### ISSUE TITLE
Odd condition when computing UCB

### ISSUE THREAD

**Issue by tawheeler** [JuliaPOMDP/MCTS.jl#56]
MCTS defaults to a visitation count of 0. The UCB calculation divides by the visitation count. To get around this, MCTS has some logic that avoids a divide-by-zero:
```julia
if c == 0 || sn == 0 || (sn == 1 && n(sanode) == 0)
    UCB = q(sanode)
else
    UCB = q(sanode) + c*sqrt(log(sn)/n(sanode))
end
```
where `c` is the exploration coefficient, `sn` is the sum over visitation counts and, and `n(asnode)` is the visitation count for the current node.
The `if` statement is a little odd. The check for `sn == 1` seems weird. Imagine a problem with 3 actions, two of which have been taken once, so the counts are [1,1,0]. With this `if` statement structure, you'll get a divide by zero because sn = 2. 

`sqrt(log(sn) / n(sanode))` approaches infinity as `n(sanode)` approaches 0 from above. Thus, any time n(sanode) is in fact zero, and c != 0, you probably want UCB to be infinity.

**Comment by zsunberg** [comment]
Hey @tawheeler , Thanks for asking!

Dividing by zero is actually fine - it results in infinity. The problem is 0/0. When sn == 1, log(sn) is zero and we get NaN.

sn == 0 results in log(sn) of -Inf, so that check is needed.

I am not sure if the c==0 check is actually needed in addition.

**Comment by tawheeler** [comment]
Ah, okay. Makes sense. Maybe a comment to that effect?

**Comment by zsunberg** [comment]
Yeah, good idea.

BTW I am thinking about re-writing this package since it is one of the more useful JuliaPOMDP package and it has some problems https://github.com/zsunberg/MonteCarloTreeSearch.jl

**Comment by zsunberg** [comment]
(The most important shortcoming of this package is that it's awkward to use outside of the strict `solve`/`action` paradigm of POMDPs.jl)
