### ISSUE TITLE
`MCTSSolver.reuse_tree=true` breaks `action_info`

### ISSUE THREAD

**Issue by gehring** [JuliaPOMDP/MCTS.jl#58]
The current implementation of `action_info(::AbstractMCTSPlanner, s)` seems to depend on the state `s` being assigned a `1` label ([relevant line](https://github.com/JuliaPOMDP/MCTS.jl/blob/67f0326e1616c43117053f75333b60956e7b11dc/src/vanilla.jl#L192)). This leads to incorrect behavior when the tree is re-used since we can no longer guarantee that state `s` was inserted first in the tree.

I believe simply replacing the hardcoded `1` to `s` fixes everything, e.g.,
```julia
function POMDPModelTools.action_info(p::AbstractMCTSPlanner, s)
    tree = plan!(p, s)
    best = best_sanode_Q(StateNode(tree, s))
    return action(best), (tree=tree,)
end
```

**Comment by zsunberg** [comment]
Thanks, good catch!
