### ISSUE TITLE
recursion in rollout

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/MCTS.jl#6]
Is there a reason that the rollout simulation is recursive rather than in a while loop? It seems like that could have a large performance penalty

**Comment by mykelk** [comment]
Yeah, doing a loop is better.

**Comment by etotheipluspi** [comment]
Its written recursively in DMU :)
It's also more compact (in code), since the backpropogation step can be handled naturally recursively. If you do a loop, you need to make sure to update all the previously visited states as you climb back up the tree.

**Comment by mykelk** [comment]
The tree policy should be recursive, but the rollout doesn't need to be. If you simulate out far enough, this can cause an issue with the recursion depth.

**Comment by etotheipluspi** [comment]
Ahh I see. Yep, then putting it in a loop is the way to go.

**Comment by zsunberg** [comment]
fixed this in a recent commit
