### ISSUE TITLE
Domain knowledge examples broken.

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/MCTS.jl#62]
A student in the DMU course at CU reported that the domain knowledge examples do not work. Need to investigate.

**Comment by zsunberg** [comment]
He reported the code at this link: https://github.com/JuliaPOMDP/MCTS.jl/blob/master/notebooks/Domain_Knowledge_Example.ipynb#Rollouts does not work.

**Comment by BoZenKhaa** [comment]
I was just playing with this and the whole notebook runs fine for me. Is there any detail to this?

**Comment by zsunberg** [comment]
Probably the student was just confused. I think it's OK to close.
