### ISSUE TITLE
Jupyter notebooks misrepresent code in Github linguist 

### ISSUE THREAD

**Issue by mossr** [JuliaPOMDP/MCTS.jl#71]
The Github linguist—which shows the breakdown of programming languages used—is often muddled by Jupyter notebooks (in the case of this repo, two notebooks take up 83% of the code and the repo is labeled as if it's written primarily in a "Jupyter notebook")

There's a quick fix that I've used elsewhere: adding a `.gitattributes` file to ignore `*.ipynb` files from the linguist:
https://github.com/sisl/POMDPStressTesting.jl/blob/master/.gitattributes

**Comment by zsunberg** [comment]
I see. do you know how long it takes to update?

**Comment by mossr** [comment]
Usually just a few minutes

**Comment by mossr** [comment]
It's updated through some background Github job so it may take longer—but that shouldn't hold back any new release

**Comment by mossr** [comment]
@zsunberg There we go :) Much better!

**Comment by mossr** [comment]
Well, I see this when clicking from the "Search or jump to..." bar:
![image](https://user-images.githubusercontent.com/1592413/92419268-490c9e80-f121-11ea-9ce0-de799a1d7769.png)

But then refreshing the page changes it back to Jupyter notebooks...so it's definitely processing.

**Comment by mossr** [comment]
Beautiful: 
![image](https://user-images.githubusercontent.com/1592413/92664870-03cfa480-f2ba-11ea-87b7-8276bda933cd.png)

**Comment by zsunberg** [comment]
Haha, beautiful indeed.
