### ISSUE TITLE
Is this a parallelized implementation?

### ISSUE THREAD

**Issue by danieljlevine** [JuliaPOMDP/MCTS.jl#96]
Hi,
I am curious if this implements a parallelized POMDP-MCTS implementation that can make use of multi-core/threading and or HPC across systems as well. Or is the search, by it's nature, not done in parallel?
Thanks!

**Comment by zsunberg** [comment]
Hi @danieljlevine . This implementation is serial. There have been various efforts to make a general parallel implementation, but I am not aware of any that have been developed into a full-featured package. If you are interested in making a parallel version, we'd be very interested in helping you!

**Comment by danieljlevine** [comment]
At the moment, I'm just trying to understand what's out there.
